name: Build Equipment Project

on:
  push:
    branches:
      - main
      - Main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest -v

      - name: Build Docker Image
        run: docker build -t all-projects-image .

      - name: Run Container
        run: docker run --rm all-projects-image > output.txt

      - name: Upload Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-projects-output
          path: output.txt

