name: Build Equipment Project

on:
  push:
    branches:
      - main
      - Main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t all-projects-image .

      - name: Run Container
        run: docker run --rm all-projects-image > output.txt

      - name: Upload Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-projects-output
          path: output.txt

      - name: Run pytest directly
        run: pytest -v
